# Route to login
/login : login

# Routes to the Demostuff delete if you are ready to
/demo/banded: 
  layout: demo
  template: demo/banded
/demo/blog:  
  layout: demo
  template: demo/blog
/demo/contact:  
  layout: demo
  template: demo/contact
/demo/feed:  
  layout: demo
  template: demo/feed
/demo/homepage-1:  
  layout: demo
  template: demo/homepage-1
/demo/homepage-2:  
  layout: demo
  template: demo/homepage-2
/demo/marketing:  
  layout: demo
  template: demo/marketing
/demo/grid:  
  layout: demo
  template: demo/grid
/demo/reality:  
  layout: demo
  template: demo/reality
/demo/sidebar:  
  layout: demo
  template: demo/sidebar
/demo/so-boxy:  
  layout: demo
  template: demo/so-boxy
/demo/store:  
  layout: demo
  template: demo/store
/demo/workspace:  
  layout: demo
  template: demo/workspace